"""SSL cert-trust auto-fix for Windows machines running antivirus SSL interception
(Avast, Kaspersky, ESET, etc. all do this: re-sign HTTPS with a locally-generated root
cert, injected into the Windows trust store, which curl_cffi/libcurl-based clients
[yfinance's transport] do NOT automatically trust — even though the OS and plain
`curl.exe` do). Root-caused 2026-07-24 as the reason yfinance `.info`/`.calendar` calls
were silently failing with CertificateVerifyError and burning multiple retries per call
before yfinance's DB-fallback kicked in — the actual cause of "Streamlit loading late"
across the whole app, not a single slow page.

Fix: export the OS-trusted root certs (which include the AV's injected one) to a PEM,
append to certifi's bundle, point CURL_CA_BUNDLE at the combined file. Self-healing and
machine-portable: only runs the (cheap, ~1s) export if a quick live test shows the
default bundle actually fails, and caches the result so later imports/restarts on an
already-working machine cost nothing.
"""
import os
import subprocess
import sys


def ensure_ssl_trust():
    """Call once at startup, before yfinance/curl_cffi is used. No-op on non-Windows or
    when the default cert bundle already works (e.g. no AV interception present)."""
    if sys.platform != "win32":
        return
    try:
        from curl_cffi.requests import Session
    except Exception:
        return   # curl_cffi not installed -- nothing to fix

    def _default_bundle_works():
        try:
            with Session(impersonate="chrome") as s:
                s.get("https://query1.finance.yahoo.com/v1/test/getcrumb", timeout=6)
            return True
        except Exception:
            return False

    if _default_bundle_works():
        return   # no interception on this machine -- nothing to do

    bundle_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "combined_ca_bundle.pem")
    if os.path.exists(bundle_path):
        os.environ["CURL_CA_BUNDLE"] = bundle_path
        if _default_bundle_works():
            return
        # cached bundle is stale (cert rotated) -- fall through and rebuild

    try:
        import certifi
        ps_script = (
            "$out = @()\n"
            "foreach ($store in @('Cert:\\LocalMachine\\Root','Cert:\\CurrentUser\\Root')) {\n"
            "  Get-ChildItem -Path $store | Where-Object { "
            "$_.Subject -match 'Avast|Kaspersky|ESET|BitDefender|generated by' } | ForEach-Object {\n"
            "    $b64 = [System.Convert]::ToBase64String($_.Export('Cert'))\n"
            "    $out += '-----BEGIN CERTIFICATE-----'\n"
            "    for ($i=0; $i -lt $b64.Length; $i+=64) { $out += $b64.Substring($i, [Math]::Min(64, $b64.Length-$i)) }\n"
            "    $out += '-----END CERTIFICATE-----'\n"
            "  }\n"
            "}\n"
            "$out -join \"`n\"\n"
        )
        result = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command", ps_script],
            capture_output=True, text=True, timeout=20)
        av_certs = result.stdout.strip()
        if not av_certs:
            return   # no AV-injected root found -- can't fix, leave default behavior
        with open(certifi.where(), "rb") as f:
            base = f.read()
        with open(bundle_path, "wb") as f:
            f.write(base)
            f.write(b"\n")
            f.write(av_certs.encode())
        os.environ["CURL_CA_BUNDLE"] = bundle_path
    except Exception:
        pass   # best-effort -- worst case, yfinance falls back to its own retry/DB path as before
