# -*- coding: utf-8 -*-
"""Build docs/IDEA_TRACKER.xlsx — one row per idea/question ever raised.

Re-runnable: edit ROWS below (or append) and re-run. Existing user edits in the sheet are
NOT preserved, so treat this script as the source of truth and add new items here.

    python tools/build_idea_tracker.py
"""
import os
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "docs", "IDEA_TRACKER.xlsx")

COLS = ["ID", "Date Added", "Raised By", "Category", "Idea / Question",
        "Detail", "Status", "Date Actioned", "Outcome / Evidence", "Commit",
        "Priority", "Next Step"]

# Status vocabulary: DONE | QUEUED | BLOCKED | REJECTED | WITHDRAWN | USER-ACTION
ROWS = [
# ---------------------------------------------------------------- security
(1,"2026-07-31","User","Security","Telegram bot token leaked on GitHub",
 "Secret scanning flagged 5 commits; live token 8407478799 exposed since 2025-12-23",
 "DONE","2026-07-31","Revoked via BotFather; new token installed; bot restarted, 0 auth errors","-","P0","-"),
(2,"2026-07-31","Claude","Security","Second bot @CE448_bot (8018716820) also leaked",
 "Token in 3 public commits; verified STILL ALIVE via getMe",
 "CLOSED","2026-08-02",
 "NOT THE USER'S BOT - closed on their instruction. Token still answers getMe (verified 2026-08-02), but it belongs to someone else so there is no revoke path from here. Its presence in this repo history remains a dangling-blob artifact only","-","P0",
 "You: @BotFather -> /revoke or /deletebot -> @CE448_bot"),
(3,"2026-07-31","User","Security","Purge git history / dangling commit 24e2ab8",
 "Asked whether to rewrite history to remove leaked tokens",
 "REJECTED","2026-07-31","filter-repo CANNOT reach dangling objects (not in clone); only GitHub Support can. Token now revoked = dead string. Rewrite would break 592 SHAs for cosmetics","-","P3",
 "Optional: dismiss GitHub alerts as 'revoked'"),
(4,"2026-07-30","Claude","Security","Full-history credential scan (all secret types)",
 "Scan for AWS/Anthropic/OpenAI/GitHub/Slack keys across 592 commits",
 "DONE","2026-08-02",
 "COMPLETE. Walked OBJECTS once (2,974 blobs <300KB) instead of walking commits - that is why the two earlier attempts timed out. Patterns: Telegram, AWS AKIA, sk-ant, OpenAI sk-, GitHub gh*_, Slack xox*, Google AIza. Result: ZERO AWS/Anthropic/OpenAI/GitHub/Slack/Google keys anywhere in history. Only 2 distinct Telegram tokens, both in UNREACHABLE (dangling) blobs: the pre-revoke token for bot 8407478799 (confirmed dead, 401) and @CE448_bot 8018716820 (confirmed still LIVE). The token currently in token.txt is live (@Analyst_Somu_AI_bot) and does NOT appear anywhere in git history","-","P2",
 "Re-run bounded to small files, in background"),
# ---------------------------------------------------------------- methodology
(5,"2026-07-31","Claude","Methodology","Pooled rank-IC t-stat is invalid on this data",
 "Random alpha expressions tested against the harness",
 "DONE","2026-07-31","68-79% of RANDOM alphas passed p<0.05 (best |t|=10.80); correct daily-IC test passes 0%. Cause: overlap + cross-correlation inflate t ~10x","5d0fa27","P0","-"),
(6,"2026-07-30","Claude","Strategy","/debate Technical agent weight 1.0 -> 1.3",
 "Raised on a backtest reporting rank-IC +0.047, t=+7.05",
 "WITHDRAWN","2026-07-31","REVERTED. That t-stat came from the broken pooled method. Correct test: t=+1.04 (5d) / +1.10 (10d) = no edge","5d0fa27","P0","-"),
(7,"2026-07-31","Claude","Methodology","Re-test 3 caveated significance claims",
 "Market Radar 'QQQ corr +0.37', Rotation 'IC +0.14', positioning 'IC +0.03' all used pooled stat",
 "DONE","2026-08-02","Re-tested under daily-IC. Rotation 'IC +0.14 p<1e-7' WITHDRAWN (t=-0.28 5d / +0.41 10d, 33 ETFs x 1500d). Market Radar '+0.37 p<0.001' DOWNGRADED to suggestive (104 overlapping days = ~21 independent; p=0.10; sign flips +0.36..-0.17 across sampling offsets). Skew panel UNTESTABLE (21 dates -> 4 independent). Both UI captions corrected and Playwright-verified","5d0fa27","P1",
 "Re-run each with daily cross-sectional IC"),
(8,"2026-07-31","Claude","Methodology","Walk-forward convention (enforced train/test)",
 "Backtests are done ad-hoc; no enforced standard",
 "DONE","2026-08-02",
 "Built tools/walkforward.py as the standard: expanding-window folds, parameter REFIT inside each fold on train only, train window stopped `horizon` short so its labels cannot peek into test, test ICs de-overlapped before any t-test, judgement on pooled TEST folds only. Convention written into .claude/rules/bot-conventions.md. Self-test on 120 tickers x 1400 days: momentum with a per-fold refit scores train IC +0.0179 vs test +0.0113, pooled t=+0.75 p=0.49 - does NOT survive; fold 5 alone reads +0.066 (t=+1.89), which is what an ad-hoc backtest would have reported. Sanity gate 2.5% (expect 5%)","-","P1","-"),
# ---------------------------------------------------------------- rec engine
(9,"2026-07-31","User","Strategy","Backtest all settled recommendations",
 "311 settled recs (236 LIVE, 75 BACKFILL)",
 "DONE","2026-07-31","LIVE = ONE rec_date into ONE expiry = 1 market outcome, no significance possible. EV rule validated: 'trap' group wins MORE (96.8%) but returns 9x LESS (+1.89% vs +16.95%)","a910cb1","P1","-"),
(10,"2026-07-31","Claude","Data","Cash-secured put capital recorded as 0",
 "risk=None for CSP in both scanners -> capital=0 -> removed from every return denominator",
 "DONE","2026-07-31","Fixed at source (risk=(K-credit)*100) in both scanners; 89 historical rows repaired. Also silently understated 'Capital at risk' on the dashboard","5c76fe7","P0","-"),
(11,"2026-07-31","Claude","Analysis","BACKFILL '+136.8% return' claim",
 "Presented as confirming the EV-rule inversion",
 "WITHDRAWN","2026-07-31","Artifact of the CSP capital=0 bug. Restated on real capital: BACKFILL +18.79% vs LIVE +14.84% - they AGREE. No inversion in BACKFILL","5c76fe7","P1","-"),
(12,"2026-07-31","User","Strategy","Exit at 50% of max profit - better?",
 "Standard premium-selling practice; reconstructed from real daily chains, ask-side closes",
 "DONE","2026-07-31","LOSES money: -$19,065 (-0.58% on capital). 73% hit target early. Worst loss IDENTICAL - zero downside protection. Caps winners, does nothing for losers","-","P2",
 "Revisit once a LOSING cohort exists; sim excludes capital-redeployment benefit"),
(13,"2026-07-31","Claude","Strategy","Cash-secured puts are the capital sink",
 "84 CSPs absorb 95.9% of capital, return 1.52%; spreads return ~14.8%",
 "DONE","2026-08-02",
 "FIXED via the concentration cap. Measured: across all 225 open recs, 75 CSPs hold 98.2% of capital at median RoR 1.10% vs 24.42% for spreads (median CSP needs $32,522 vs $164). Under 'Highest POP' ranking CSPs took 49.7% of a $10k basket; the new 'Max per position (% of capital)' cap (default 25%) drops that to 0% without banning CSPs outright - they simply cannot exceed their share","a910cb1","P1",
 "Filter or shrink CSPs in the basket sizer"),
(14,"2026-07-31","Claude","Strategy","Basket sizer deploys only 27% of $10k",
 "EV ranking picks cheap spreads, leaves $7,276 idle -> -0.21% after fees vs +21.56% at full deployment",
 "DONE","2026-08-02",
 "FIXED. Root cause was `_lots = 1` for the EV/POP rules, so the basket took one contract of each cheap spread regardless of account size. Added a scale-up pass (add lots in ranked order to a Target deployment %, skipping premium traps) plus a per-position concentration cap. Measured: $10k 45.9% -> 90.2% deployed (EV +222 -> +591); $50k 9.2% -> 90.0%; $250k 1.8% -> 90.3%, largest position always <=25%. Verified in the live DOM: $9,020 deployed, 90% of capital, zero exceptions","-","P1","Fix the deployment flaw"),
# ---------------------------------------------------------------- regime / hedging
(15,"2026-07-31","User","Strategy","Performance during market falls",
 "Claimed impossible pre-2026-07; user pushed back - correctly",
 "DONE","2026-07-31","I was WRONG. Outcomes depend only on the underlying, and stock_history reaches 1990. A 6-7% index drop = -100% on the spread. SPY 2022 = -179% on risk, erasing 2019+2021 combined","cb53358","P1","-"),
(16,"2026-07-31","User","Strategy","Index vs individual stocks - which is better?",
 "Common window 2020-08 to 2026-07 so every ticker sees 2022",
 "DONE","2026-07-31","NOT SIGNIFICANT (t=1.49, p=0.186). Withdrew a contaminated ranking - 6 tickers lacked pre-2020-07 history and skipped COVID. Within-stock dispersion dwarfs the index/stock gap","cb53358","P1","-"),
(17,"2026-07-31","User","Strategy","Hedge strategies for continuous income",
 "Tail put / collar / vol filter / wide-OTM tested on real crash cycles",
 "DONE","2026-07-31","Tail puts are -EV once REAL skew is priced (SPY 10% OTM = 1.80x ATM IV). TAIL PUT -506%, COLLAR -4016%. WIDE OTM best (+271%). Position sizing is the hedge, not options","d55400d","P1","-"),
(18,"2026-07-31","Claude","Methodology","Flat-vol pricing reversed every hedge conclusion",
 "First run priced all options at one ATM vol",
 "DONE","2026-07-31","Measured real skew in our own chains, refit, and TAIL PUT went +223% -> -506%. Caught before reporting as final","d55400d","P0","-"),
# ---------------------------------------------------------------- external tools
(19,"2026-07-30","User","Research","Review awesome-systematic-trading repo",
 "295 entries across 13 sections tabulated",
 "DONE","2026-07-30","Adopted volest (range-based vol estimators, shipped into /vrp) and the vectorbt pattern (60x faster, identical rank-IC)","e355ef7","P2","-"),
(20,"2026-07-30","User","Research","Private AI quant platforms survey",
 "GitHub API vitals, not marketing pages",
 "DONE","2026-07-30","QuantMuse flagged as a trap: 2,824 stars but 9 commits / 1 contributor. Category already absorbed by this project","c9da836","P2","-"),
(21,"2026-07-31","User","Research","QuantConnect / LEAN for backtests?",
 "Evaluated against limitations this session exposed",
 "DONE","2026-07-31","Worth a RESEARCH trial, not migration. Only thing carrying years of real option quotes w/ bid-ask (AlgoSeek + ThetaData). Will not fix statistical discipline","714cc33","P2",
 "Verify options data cost + coverage start dates"),
(22,"2026-07-31","User","Research","Quantiacs for backtests?",
 "Head-to-head vs QuantConnect, API-verified",
 "REJECTED","2026-07-31","NO options data at all. Toolbox 82 stars, ~7mo stale. Category mismatch for an equity-options book","7fe7c46","P3","-"),
(23,"2026-07-31","User","Research","Proven/backtested income-hedge strategies on GitHub",
 "Searched and verified claims",
 "DONE","2026-07-31","Headline '24.95% CAGR put selling' came from a repo with 0 commits / 0 contributors, and was internally contradictory. Real evidence base is CBOE BXM/PUT indices, not GitHub","-","P2","-"),
# ---------------------------------------------------------------- storage / schema
(24,"2026-07-31","User","Infra","How much disk does the data occupy?",
 "Measured empirically, one real day copied to temp DB",
 "DONE","2026-07-31","70.4 MB/trading-day -> ~18.2 GB/yr. 23 GB free = ~1.3 years runway","-","P1","-"),
(25,"2026-07-31","Claude","Infra","Drop options_daily as a duplicate",
 "Proposed on matching row counts",
 "WITHDRAWN","2026-07-31","WRONG - compared rows not schema. It has 29 extra columns and 20+ live read sites. Renaming would break /oi, ticker detail, expiry breakdown within minutes","-","P1","-"),
(26,"2026-07-31","Claude","Infra","Pre-July rows are irreplaceable",
 "Inverted my own archival advice",
 "DONE","2026-07-31","options_openbb starts 2026-07-02; options_daily starts 2025-12-12; US_data.db is EMPTY. Pre-July rows are the ONLY copy of Dec-Jun and cannot be regenerated","-","P0",
 "Back these up FIRST, delete last"),
(27,"2026-07-31","Claude","Infra","Drop 18 dead columns from options_daily",
 "money_*, vol_rank_*, *_info, chg_oi_* - zero references anywhere",
 "QUEUED","","Measured 16.7% smaller (18.6 -> 15.5 MB/day), ~0.24 GB/yr. Zero read sites change","-","P2",
 "Verify refs, back up schema, ALTER, VACUUM"),
(28,"2026-07-31","User","Infra","Consolidate onto options_openbb only, drop options_daily",
 "Asked whether to migrate fully",
 "QUEUED","","VIABLE - only 3 of 29 cols genuinely needed (company_name/asset_type/load_date); 18 dead, 8 OHLC only 0.4% populated post-July. Catch: pre-July has no options_openbb source, so merging breaks the 'every row has real quotes' invariant","-","P2",
 "Deferred by user - revisit when read paths need refactoring anyway"),
(29,"2026-07-31","Claude","Infra","Parquet archival as standing policy",
 "Parquet is 19x denser (3.7 vs 70 MB/day)",
 "DONE","2026-08-02",
 "Built tools/archive_parquet.py: exports one parquet per trade_date, then RE-READS it and compares row count, column set and a per-column checksum against SQLite before marking the day safe_to_prune. Fingerprint sorts each column independently because parquet round-trips can reorder rows. Script NEVER deletes; --verify-only re-checks an existing archive. Archived the 5 oldest options_openbb days (883,234 rows): 320.0 MB -> 19.7 MB, 16.2x denser, 5/5 VERIFIED on readback and again from disk. Archive lives outside the repo at Options_chain_data/archive_parquet","-","P1",
 "Export + VERIFY readback before any delete"),
(30,"2026-07-30","Claude","Data","CBOE quote drifted from chain snapshot",
 "Backfilled underlying_price from a separately-timed quote",
 "DONE","2026-07-31","AAPL 6.4% / AMZN 9.4% off on their earnings evening. Switched to put-call parity off the same snapshot - internally consistent by construction","-","P1","-"),
(31,"2026-07-30","Claude","Infra","SQLite 'database is locked' killed a 734-ticker run",
 "My ad-hoc backfill collided with the EOD capture at 11%",
 "DONE","2026-07-30","busy_timeout=30s added to every writer across all capture scripts","-","P0","-"),
# ---------------------------------------------------------------- research queue
(32,"2026-07-31","Claude","Research","Inverted-edge test",
 "scn_revert / gex / left_skew have 95% CIs entirely BELOW 50%",
 "DONE","2026-08-02","NO inverted edge. scn_revert (1162 fires) spans only 17 dates; collapsing dates flips hit rate 45.3% -> 53.9%, scn_zrev 43.3% -> 53.2%. The sub-50% CIs were fire-clustering, not signal. gamma_pin p=0.019 is 1 of 13 models tested at n=6 dates - not evidence. No inverse scanner built (closed as a save)","-","P1","-"),
(33,"2026-07-31","Claude","Research","Realistic fill modelling",
 "Every backtest except the 50%-exit test assumes mid-price fills",
 "DONE","2026-08-02","Measured on real options_openbb bid/ask for 204 settled put recs. Median short-leg spread 17.6% of mid (75th 35.8%, 90th 54.4%). Mean return mid +7.25% -> +3.81% at a midway fill = mid-pricing overstates ~2x. Win rate barely moves (94.6->94.2) - the spread eats the credit, which IS the edge. 13 recs have no positive credit at all at f=0.5","-","P1","-"),
(34,"2026-07-28","Claude","Research","Skew-panel backtest (does skew predict downside?)",
 "Gate was ~15-20 dates; rerun at 17",
 "DONE","2026-07-28","pcoi crosses significance (rank-IC -0.058, t=-3.17, correctly signed); skew25/pcvol directional but not significant. Flagged promising-not-conclusive, no scanner built",
 "42b3ab4","P2","RE-TEST: that t-stat used the pooled method later proven invalid (see ID 5)"),
(35.5,"2026-07-31","Claude","Research","Dispersion (#14)",
 "Index IV vs constituent vol",
 "QUEUED","","Separate from the skew backtest; never built, no data gate identified","-","P2","-"),
(35,"2026-07-31","Claude","Research","Formulaic alpha discovery (AlphaGen/Genetic-Alpha)",
 "Initially ranked #1 for highest ceiling",
 "REJECTED","2026-07-31","DOWNGRADED to do-not-build. It is an overfitting machine; on this sample it would find exactly the garbage the random-alpha test just found","-","P3",
 "Revisit only with walk-forward + corrected harness"),
(36,"2026-07-31","Claude","Research","Cross-strategy capital allocator",
 "Size capital across strategies by measured edge",
 "BLOCKED","","~262 graded fires/model gives a 12-point 95% CI - a 44% model is indistinguishable from 50%. Needs n~1000 (~7 months)","24c6a8b","P2","-"),
(37,"2026-07-31","User","Feature","EOD digest like InsiderFinance newsletter",
 "Reviewed each section for feasibility",
 "DONE","2026-08-02",
 "Built /digest (_eod_digest) with the 4 buildable sections: headlines, sector rotation, live option setups, unusual activity. Each states what it is worth - rotation carries the measured quadrant result, UOA is labelled descriptive-not-predictive (47.1% hit = coin flip), POP labelled model output. 5th section (AI Noteworthy Trades) omitted on purpose: needs per-print time-and-sales with aggressor side, which no free feed provides. Found and fixed 3 defects while verifying: rotation used a non-existent `item` key, 4 legacy CSP rows still carried the capital=0 bug (repaired in DB), and the RSS mix was leaking personal-finance advice columns into a market digest","-","P2","-"),
(38,"2026-07-30","User","Feature","Ollama local-LLM narrative synthesis",
 "worldmonitor pattern; free, no API cost",
 "BLOCKED","","Needs Ollama installed - your call","-","P3","-"),
(39,"2026-07-24","User","Feature","NSE / India lane",
 "Endpoints verified (bhavcopy has real delivery %)",
 "QUEUED","","Not blocked, just large: own DB, EOD script, /india command, dashboard section","-","P3","-"),
(40,"2026-07-22","User","Research","Kronos foundation model",
 "Open-source K-line foundation model",
 "BLOCKED","","Pretrained through an unpublished cutoff - backtesting on our history is contaminated and would manufacture a fake edge","-","P3","-"),
# ------------------------------------------------- added on re-audit vs all 76 commits (2026-08-01)
(41,"2026-07-31","Claude","Strategy","~100% POP recommendations were fake",
 "Some recs showed POP=100, which is impossible",
 "DONE","2026-07-31","Root-caused and fixed; fake-POP recs also excluded from the capital basket","2a172ba","P0","-"),
(42,"2026-07-31","User","Feature","Capital-deployed basket sizing (start with $10k)",
 "User: if i want to start with 10k, what should i take and track them",
 "DONE","2026-07-31","Basket sizer with persistent tracking; then found it deploys only 27% of capital (see ID 14)","40c2e31","P1","-"),
(43,"2026-07-31","Claude","Strategy","Per-row EV verdict on the basket + debit-spread fix",
 "paid% vs need% shown per row",
 "DONE","2026-07-31","Debit spreads computed max profit wrongly; fixed. This is the column later validated by the 311-rec backtest","9b80d13","P1","-"),
(44,"2026-07-30","User","Data","Stop using Yahoo for stock_daily",
 "User: why are we using yahoo, use only bb",
 "DONE","2026-07-30","Sourced close from BB own underlying_price; zero extra API calls, immune to yfinance rate-limiting","99945d1","P1","-"),
(45,"2026-07-30","Claude","Research","A18 short-interest validation",
 "Was blocked ~2-3 months on history accruing",
 "DONE","2026-07-30","UNBLOCKED ~7mo early via free Nasdaq historical API. Honest NULL result: rank-IC +0.017 (t=+0.65), no edge. Kept descriptive","49fd0c2","P2","-"),
(46,"2026-07-29","User","Feature","Rotation Tracker drilldown",
 "User: if sectors in green like health care it should point me stocks",
 "DONE","2026-07-29","Click the chart bubble directly to drill sector into constituent stocks","2f836c8","P2","-"),
(47,"2026-07-29","User","Feature","Add Victoria Fernandez / CrossMark to 13F tracker",
 "User asked to add her portfolio",
 "DONE","2026-07-29","CrossMark Global Holdings added to _EDGAR_FUNDS","0279b7a","P3","-"),
(48,"2026-07-29","User","Bug","FOMC info missing from the wrap",
 "User: where is today FED meeting info, why that missing",
 "DONE","2026-07-29","Added FOMC-today flag, full indices table, and a major-world-events scan (wars/bombings/climate per user ask)","7bdf903","P1","-"),
(49,"2026-07-28","User","Feature","M2 money supply + gold/dollar in daily alerts",
 "User asked for money-supply insight and its relation to gold/dollar",
 "DONE","2026-07-29","Added to Market Overview and the daily brief with a 5y chart. Computed the REAL correlation (weak: gold -0.10, DXY -0.03) instead of asserting the popular narrative. Later added QoQ + pipe-table format","d273612 a57abca 8e89734","P2","-"),
(50,"2026-07-28","User","Feature","Watchlist: company names + edit capability",
 "User: charts dont have names, also after ticker place the name",
 "DONE","2026-07-29","Name column, chart titles, and an Edit panel (asset class / target / note)","11352fc","P2","-"),
(51,"2026-07-28","Claude","Strategy","Exit Planner liquidity gate",
 "BS next-day model recipe: vol>=100, spread<=8%",
 "DONE","2026-07-28","Validated recipe wired into Day L-H scenario pricing; thin legs flagged","7f87e11","P2","-"),
(52,"2026-07-28","Claude","Feature","A10: consolidate recurring alerts into one message",
 "~5 recurring pushes filling the chat",
 "DONE","2026-07-28","position_monitor + intraday_alert folded into ONE edited status message per day. Trigger-only alerts left separate on purpose (they are genuine news)","1563870","P2","-"),
(53,"2026-07-28","User","Feature","README demo video of the app + Telegram",
 "User: i want video not GIF, also all pages",
 "DONE","2026-07-28","Recorded a real MP4 tour of all 35 dashboard pages via Playwright; kept GIF markdown links per user preference","70416a8 973346e 04beb6e","P3","-"),
(54,"2026-07-28","Claude","Feature","Verdict-grounding RAG",
 "Retrieve news/sentiment/13F context for a fired verdict",
 "DONE","2026-07-28","Extended corpus, deduped the MCP/bot RAG core into one implementation, wired into the UI. Verified live via Playwright","3e14b29","P2","-"),
(55,"2026-07-27","User","Bug","OI charts not appearing",
 "User: why is not getting two pictures of charts in OI, we build that",
 "DONE","2026-07-27","Two causes: Telegram flood control on rapid photo sends, then the REAL one, wired into the wrong handler","b191f43 d84e40f","P1","-"),
(56,"2026-07-27","User","Bug","Chart text illegible / spot line invisible",
 "User: color is light and cant see that, and: $61 expected day, what is this",
 "DONE","2026-07-27","Fixed an overlapping annotation collision, then the invisible white spot-line/bar on a white background; bumped text sizes","46a43fb 4e3c2a2","P2","-"),
(57,"2026-07-27","User","Bug","Earnings call transcripts stuck a quarter behind",
 "User: earning call is not latest",
 "DONE","2026-07-27","Real bug: quarter calculation used the CURRENT in-progress quarter. Also fixed CALL HIGHLIGHTS silently showing a stale quarter","be21f08 5591370","P1","-"),
(58,"2026-07-27","User","Bug","Daily alerts trimmed / showing literal HTML",
 "User: daily alerts are trimmed, many sections are not there",
 "DONE","2026-07-27","Root cause: _tg_balance did not recognise <blockquote expandable> as an opener, so every real closer was deleted as an orphan","d4c9e51","P0","-"),
(59,"2026-07-27","User","Feature","News hyperlinks everywhere",
 "User: I asked for hyperlinks to read full news",
 "DONE","2026-07-27","URLs threaded through position alerts, OI ticker view, world news; later the /wrap catalyst quote too","9129bb2 0349c62","P2","-"),
(60,"2026-07-27","Claude","Bug","yfinance silently failing on every .info/.calendar call",
 "Found during a performance investigation",
 "DONE","2026-07-27","Root cause was environment-level: antivirus SSL interception. Built a self-healing trust fix","bd11d4f","P0","-"),
(61,"2026-07-27","User","Feature","Geopolitical / supply-chain risk flag",
 "User asked for wars, bombings, climate severity in alerts",
 "DONE","2026-07-27","Country instability flags wired into /catalysts; fires only on a real match","2331abb","P2","-"),
(62,"2026-07-26","Claude","Feature","/debate Bull-vs-Bear round + prose polish",
 "TradingAgents-inspired adversarial round",
 "DONE","2026-07-27","Structured Action/Entry/Stop/Target verdict sized off real 5d realized vol; optional LLM polish with a bulletproof fallback","69e23a0 bd74c1f","P2","-"),
(63,"2026-07-27","Claude","Feature","Persistent preference memory",
 "hermes-agent pattern",
 "DONE","2026-07-27","ticker_interest table; /debate logs views, Watchlist orders by them","c456717","P3","-"),
(64,"2026-07-25","User","Bug","Closed Positions section disappeared",
 "User: i dont see closed positions section anymore",
 "DONE","2026-07-25","Real cause: a stray unconditional st.stop()","4924a35","P1","-"),
(65,"2026-07-26","Claude","Infra","Delete confirmed-dead _lib modules",
 "A16 orphan triage",
 "DONE","2026-07-26","Removed 3 modules with zero call sites after verifying the underlying tables stay alive via separate direct code","d47908d","P3","-"),
(66,"2026-07-27","Claude","Feature","A5 OI buy-to-open vs write-to-open classifier",
 "Rising OI alone is ambiguous",
 "DONE","2026-07-27","OI x price self-join. Verified live: several BULLISH call builds are actually >95% write-to-open","bc5373e","P2","-"),
(67,"2026-07-27","Claude","Infra","Audit-table closeout (A1/A11/A12/A15/A16)",
 "Several rows were stale or already fixed",
 "DONE","2026-07-27","Exit Planner reorder via st.empty(); Market Overview collapsed; Portfolio page verified live via Playwright (first time ever opened); A16/A1 confirmed false alarms","3bc98b1 7ca1296 b66d220 5c267a2 d3895e8","P2","-"),
(68,"2026-08-01","User","Process","Maintain an Excel tracker of ideas/questions",
 "One row per idea, actioned flag, date added, date actioned",
 "DONE","2026-08-01","Built IDEA_TRACKER.xlsx + regenerator; force-added past .gitignore with approval. Re-audited against all 76 session commits and added ~30 missing rows","8187857","P2","-"),
(69,"2026-07-27","User","Question","Do we have MCP connectors (GitHub/Brave/Supabase/Notion/Figma)?",
 "Asked which connectors are available",
 "DONE","2026-07-27","Only claude.ai Google Drive is configured and it needs auth. Git/GitHub MCP judged unnecessary since plain git/gh CLI covers this workflow","-","P3","-"),
(70,"2026-07-31","User","Question","Intraday alerts not arriving, only anomaly ones",
 "User asked why",
 "DONE","2026-07-31","Tabulated all 24 scheduled jobs and their trigger conditions; most are market-hours or state-change gated","-","P2","-"),
(71,"2026-07-28","Claude","Infra","Sidebar rebrand to WallStreet_Agentic_TradeOps",
 "Repo renamed from NYSE_DATA",
 "DONE","2026-07-28","Heading text + font size","8c46bb8 f414493","P3","-"),
# ------------------------- added 2026-08-01: repo asks that were done but never tracked
(72,"2026-07-24","User","Research","Scraping tools: which is best? (crawl4ai / firecrawl)",
 "User gave both repos: unclecode/crawl4ai and firecrawl/firecrawl, asked to analyse, plan, then do",
 "DONE","2026-07-24","Shortlisted Firecrawl (~155k stars, cloud or self-host) vs Crawl4AI (~75k, Playwright-based, LLM-ready markdown) vs Playwright (already installed). Recommendation: Playwright for one-off JS pages, Crawl4AI only if recurring structured scraping starts. Neither installed - not needed. Written up in docs/SCRAPING_TOOLS.md",
 "-","P3","-"),
(73,"2026-07-24","Claude","Methodology","TradingKey was assumed JS-gated - it was not",
 "The reason the scraping-tool question came up at all",
 "DONE","2026-07-24","Checked the raw HTML properly: page is server-rendered (Next.js SSR) and ships all 88 investors as a JSON blob. Plain requests.get + ?page=N works. No browser needed. Lesson recorded: verify the raw HTML before reaching for browser automation",
 "-","P2","-"),
(74,"2026-07-24","User","Research","worldmonitor / TradingAgents / hermes-agent",
 "User gave 3 repos as a possible AI hedge fund desk architecture",
 "DONE","2026-07-27","Wholesale adoption rejected (TradingAgents needs paid LLM calls per decision; the other two are large standalone products). Scoped 4 smaller pieces instead - 3 shipped (Bull-vs-Bear round, prose polish, geopolitical flag, preference memory), 1 deferred (Ollama, needs install)",
 "69e23a0 bd74c1f 2331abb c456717","P2","-"),
(75,"2026-07-25","User","Feature","virattt/ai-hedge-fund",
 "Multi-persona investor ensemble",
 "DONE","2026-07-25","Borrowed the PATTERN, not the dependency: built the AI Hedge Fund dashboard page as a free/deterministic rule-based ensemble (no LLM keys, no paid data). Confirmed in the Part 2 survey as already-absorbed",
 "-","P2","-"),
(76,"2026-08-02","Claude","Strategy","Scanner liquidity gate + realistic fill",
 "Direct follow-up to the ID 33 fill measurement",
 "DONE","2026-08-02","Added _hp_fill (shared by _hiprob_scan and _hiprob_scan_asof): rejects legs with no two-sided market or spread >35% of mid, and prices shorts at the sell side / longs at the buy side (f=0.50) instead of the mid. Verified on the 2026-07-21 universe: all 15 setups still qualify, credits fall a median 7% (up to 31% on two-leg spreads, 0.3% on index CSPs). Gate bites where measured: EFA rejects 79% of legs, SPXS 75%, BIIB 53%, liquid mega-caps 0%. Live yfinance path smoke-tested",
 "-","P1","-"),
(78,"2026-08-02","User","Feature","GEX Master Trading co-pilot (Nick Ireland framework)",
 "User pasted the full two-mode co-pilot spec; Claude initially read it as forwarded reading material and did NOT action it - caught by the user the next day",
 "DONE","2026-08-02","Built /gexplan (Mode 1 pre-market blueprint) and /gexcheck (Mode 2 live execution filter). Improves on the source prompt by auto-filling gamma flip / call wall / put wall / control node from our OWN captured chain via _compute_gex + analyze_inst_signals, instead of pasting them by hand from SpotGamma. Adds the daily 9/21/50 EMA trend gate (Bullish/Bearish/Tangled -> no-trade) and the 3-part checklist as a hard gate. Fixed a real defect during verification: the control node was picked from walls banded around the MEDIAN strike, giving SPY a $550 node against a $756 spot - now constrained to +/-10% of spot. Carries an honesty footer: on this DB the gex model hit 40.2% over 107 fires, p=0.21 de-overlapped, so levels are structure not forecast; the value is the filter",
 "-","P2","-"),
(79,"2026-08-02","Claude","Process","A pasted spec was treated as reading material, not a task",
 "The GEX prompt arrived as a forwarded WhatsApp-style thread and was answered with a critique instead of being built or logged",
 "DONE","2026-08-02","Owned and corrected. Lesson: when the user pastes a spec, log it in the tracker even if unsure whether to build it - the tracker exists precisely so an ask cannot be silently dropped. Nothing else from that day was missed (re-checked the session)",
 "-","P2","-"),
(80,"2026-08-02","User","Feature","GEX co-pilot: complete the checklist + merge the gamma pages",
 "User asked whether everything in the GEX spec existed in BOTH Telegram and Streamlit, then to merge the duplicate gamma tabs",
 "DONE","2026-08-02","Audit found 3 gaps: price-action and volume legs were only PRINTED as requirements (so a GREEN LIGHT could fire on structure alone), no 0DTE/weekly expiry choice, and NOTHING in Streamlit. All closed. (1) _gex_confirm reads real 1m bars from US_intraday.db - volume vs 20-bar mean (>=1.5x) and rejection-candle / 9-EMA-reclaim detection; tickers outside the 32-name intraday lane report UNVERIFIED and FAIL the leg rather than pass unseen. (2) expiry basis selector: SPY reads TRENDING -16M on the monthly but PINNING +43M on 0DTE - opposite regimes at the same moment. (3) merged the two dedicated pages (GEX Profile, Gamma Wall Advisor) into one 'GEX Command' page with a sidebar sub-view + new Co-Pilot view; GEX sections inside OTHER pages left untouched per user instruction. Verified in live DOM",
 "-","P2","-"),
(81,"2026-08-02","User","Research","Can anything be salvaged from GEX?",
 "Asked after being told the GEX levels have no measured edge",
 "DONE","2026-08-02","Found we had been testing the WRONG CLAIM: every prior test scored GEX on DIRECTION (40.2% hit, p=0.21), but dealer-hedging theory makes no directional claim - it predicts realised VOL. Tested properly. First harness gave IC +0.146 t=+3.85 p=0.0008 but FAILED its sanity gate (15% of random signals passed) - discarded, not reported. Causes: cross-ticker level effect + vol persistence. Framed as the theory actually states it (time-series, per-underlying): SPY high-GEX days -> 10.2% fwd vol vs 14.0% after low-GEX; QQQ 16.6% vs 23.6%. Correctly signed and economically large (~27-30% lower) but n=12/bucket, p=0.06-0.09, NOT significant. Conclusion: keep GEX as a volatility-REGIME read for sizing/strategy choice, never for direction; do not build a directional GEX scanner. Re-test at >=40 obs per bucket. ADOPTED.md Part 10",
 "-","P2","Re-test when ~8 more months accrue, or sooner using options_openbb real gamma"),
(82,"2026-08-03","User","Feature","Master-investor screeners (Graham / Fisher / Munger + more)",
 "User asked for stock screeners based on the classic investing models",
 "DONE","2026-08-03","Built /screen with 8 models: graham, fisher, munger, buffett, lynch, greenblatt, schloss, oneil. Fundamentals from yfinance cached 7 days in yf_info_cache (quarterly data - faster refresh just re-downloads the same numbers). Checked whether OpenBB could source these instead: fundamental.ratios is fmp/intrinio only (both paid) and fundamental.metrics free path IS yfinance, so OpenBB adds a wrapper, not data - and it currently fails with the antivirus SSL-interception error that bd11d4f fixed for yfinance. Verified on 30 large caps: Lynch picks MU 7/7, GOOGL 6/7; Munger picks GOOGL/MU/META/PG/NFLX 7/7",
 "-","P2","Point-in-time fundamentals needed before any backtest is possible"),
(83,"2026-08-03","Claude","Methodology","Fundamental screens cannot be backtested here",
 "Raised while building the master screeners",
 "DONE","2026-08-03","We store only the CURRENT fundamentals snapshot. Scoring past prices against todays numbers is look-ahead bias and would manufacture a fake edge - the same failure class as ADOPTED.md Parts 4 and 9. Screens therefore ship labelled NOT BACKTESTED / research filter, not validated signal. Noted that O Neil CANSLIM is the one model whose PRICE half (52wk-high proximity, move off the low) is genuinely testable, because we own price history back to 1990",
 "-","P2","Option: capture a fundamentals snapshot weekly to build point-in-time history going forward"),
(84,"2026-08-03","User","Bug","Scanner tables showed only ONE side of a two-sided signal",
 "User: /revert shows only oversold, /rs shows no laggards - yet the footer names the hidden tickers",
 "DONE","2026-08-03","Systemic, not a one-off: rows are sorted most-extreme-of-one-side first and then cut with rows[:15], so the opposite tail can never survive the cut while the legend still promises two colours. Added a shared _both_tails() helper and wired it into revert / zrev / breakout, plus a head+tail slice for rs. Verified live: revert has 56 oversold + 52 overbought and showed 15/0 before, now 8/7; rs 190 leaders + 280 laggards, was 10/0, now 7/5; zrev 15/15 -> 8/7; breakout 45/17 -> 8/7",
 "-","P1","Audit vrp / pairs / uoa / positioning for the same pattern - they were too slow to include in the sweep"),
(85,"2026-08-03","User","Feature","Master screeners on the Streamlit side too",
 "User asked whether /screen was added to the dashboard",
 "DONE","2026-08-03","It was Telegram-only. Added all 8 models to the Strategy Scanners page dispatcher, reusing _screen_masters from the bot engine - no logic duplicated. Columns richer than Telegram allows: Name, Sector, Score, P/E, P/B, ROE, D/E, gross margin, and which tests each name MISSES",
 "-","P2","-"),
(86,"2026-08-03","User","Feature","Make /pairs action-oriented",
 "User: what is this, give a trade-oriented message",
 "DONE","2026-08-03","Added _pairs_plan(): converts a z-score into an actual trade - share counts per leg sized off the beta hedge ratio on $10k gross, target (z->0) with expected $, stop (z widens 1 sd) with expected loss, reward:risk, and a TIME STOP at 2x half-life on the reasoning that if it has not reverted in the time the model implies, the relationship has changed rather than the trade being early. Kept the uncapped-loss / needs-borrow warning explicit",
 "-","P2","-"),
(87,"2026-08-03","User","Bug","/vrp took ~44 minutes",
 "User reported /vrp is very slow",
 "DONE","2026-08-03","Profiled rather than guessed: _iv_rank measured 5.6 SECONDS per ticker x 471 in SCAN_UNIVERSE = ~2,637s. Same anti-pattern already fixed in _uoa_scan - read a ticker whole options history then walk it with groupby+iterrows calling strptime on every row against 4 candidate formats. DB dates are ISO so one vectorised to_datetime replaces all of it, and one bulk query replaces 471. Result: cold 55.7s, warm 4.4s (47x). Regression-tested against the retained legacy implementation on 8 tickers: iv and rank identical to 5 decimal places, 8/8",
 "-","P1","Cold path is still 55.7s; the remaining cost is _daily_ohlc per ticker if it needs further work"),
(88,"2026-08-03","Claude","Bug","Two functions named _iv_rank; the yfinance one is dead",
 "Found while profiling /vrp",
 "DONE","2026-08-03","_iv_rank(sym) at line ~1344 (yfinance HV-based) is shadowed by _iv_rank(conn, tk) at ~24750 defined later. The first is unreachable dead code. Left in place for now and documented rather than deleted mid-perf-work",
 "-","P3","Delete the shadowed yfinance _iv_rank after confirming zero call sites"),
(89,"2026-08-03","User","Docs","Runbook: run each surface standalone + clone/bootstrap",
 "User asked for git commands to run streamlit/telegram independently and to clone/organize",
 "DONE","2026-08-03","Wrote docs/RUNBOOK.md: standalone run commands for all four surfaces, the PowerShell bot-restart recipe (the bot does not hot-reload, Streamlit does), an explicit table of what is NOT in git and how to get each piece back, the full clone -> venv -> requirements -> restore-from-Drive -> recreate-secrets -> first-run sequence, scheduled tasks, health checks, backup state, and the gotchas that actually bite (ASCII console, canvas-rendered tables, as-of DTE, never pooling LIVE with BACKFILL, stale yfinance chains). Also corrected the CLAUDE.md line that claimed the bot auto-launches the dashboard",
 "-","P2","Second offsite target - today both copies are effectively on one machine until Drive syncs"),
(90,"2026-08-03","User","Process","Log mid-task messages to the sheet, finish current task first",
 "User: if I send new messages before you finish, keep them in the sheet, analyse, and do them in order",
 "DONE","2026-08-03","Agreed and adopted as a working rule; written into CLAUDE.md. Rationale: mid-turn messages were being answered opportunistically, which meant some were half-answered and at least one (the world map) was BUILT but never wired to a command because attention moved on. Protocol now: finish the in-flight change, log every new ask as a tracker row immediately, then work them in the order given",
 "-","P1","-"),
(91,"2026-08-03","User","Bug","Short interest says no data for GOOG but the DB has 25 rows",
 "/squeeze and the SI panel show: GOOG - no short-interest data",
 "DONE","2026-08-03","Confirmed: short_squeeze_signal read ONLY yfinance .info and never touched our short_interest table. Precise trigger: yfinance returned shortPercentOfFloat=None for GOOG while still giving shortRatio=2.47 and sharesShort=58.5M - the panel keyed off the one missing field and declared no data. Three-layer fix: (1) derive pct from sharesShort/floatShares when yfinance omits it, (2) fall back to our own short_interest capture (1,590 rows / 64 tickers), (3) only then say no data. Also fixed the display - :.0f printed SI 0% for anything under 0.5%, which reads like missing data on the mega-caps that are genuinely barely shorted. Now: GOOG 0.5%, AAPL 1.0%, NVDA 1.4%, TSLA 2.0%",
 "-","P1","-"),
(92,"2026-08-03","User","Question","Morning brief does not mention Japan / the yen",
 "User asked whether current topics are being picked up at all",
 "DONE","2026-08-03","Audited: the morning brief covered ES, NQ, VIX, Gold and Oil ONLY - there was no FX and no international index anywhere in it, so an overnight yen or Nikkei story could not possibly appear. Nothing was looking. Fixed at the source by adding FX and RATES as a first-class region in the shared _MKT_SPECS list (USD/JPY, EUR/USD, DXY, US 10Y), which flows to every markets surface at once, and by including the regional world block in the brief. Also fixed FX precision - whole-number formatting had printed EUR/USD as 1 and the 10Y as 5. Validated on the day it was raised: USD/JPY -1.91%, the very move that prompted the question",
 "-","P1","-"),
(93,"2026-08-03","User","Feature","Macro dashboard: 12 months, revisions, MoM and YoY",
 "User: extend the table to the last 12 months, handle revisions, add a timeline plus MoM/YoY, and advise",
 "QUEUED","","Currently a single-point snapshot per indicator. Revisions matter - BLS restates NFP - so a stored history is needed to show what a print was ORIGINALLY vs now",
 "-","P2","Store each print with its vintage; render 12m sparkline + MoM/YoY columns"),
(94,"2026-08-03","User","Question","Why does it say Set FRED_API_KEY",
 "Comment appears under the macro dashboard",
 "DONE","2026-08-03","Verified the key IS consumed - _fred_latest() at telegram_bot_optimized.py reads os.environ FRED_API_KEY - so the hint was legitimate, not dead. It was simply useless as written. Rewritten to say what the figures above ARE (keyless lane: BLS prints + live market yields), what a key ADDS (full St. Louis Fed series - history, revisions, many more indicators), where to get one free, and exactly where to put it (FRED_API_KEY=... in api_keys.env)",
 "-","P3","-"),
(95,"2026-08-03","User","Bug","Cryptic table headers (12-1, Rk/D, Hit%/Now)",
 "User: I do not understand these headers",
 "DONE","2026-08-03","Added real legends. 12-1 now reads: 12-month return EXCLUDING the last month, the standard momentum measure, skipping a month avoids short-term reversal. Rk = rank in the universe, 1 = strongest. Rk/D = rank / decile, decile 1 = strongest 10%, 10 = weakest. Verified rendering. Note my first note on this row was WRONG - Rk/D is rank/DECILE, not rank/change-in-rank",
 "-","P2","-"),
(96,"2026-08-03","User","Feature","Profit bars for positions",
 "User asked for bar indicators like the 52w one, on P&L",
 "QUEUED","","Flagged a real problem back: a progress bar needs a BOUNDED range and P&L has none (a CSP loss is unbounded, a long option can be +400%). Offered three bounded alternatives - percent of max profit captured on a defined-risk spread, percent of capital at risk consumed, distance to breakeven as a fraction of cushion - and asked which is wanted",
 "-","P2","Awaiting the user choice of denominator"),
(97,"2026-08-03","User","Feature","Freeze Ticker/Spot on EVERY Streamlit table",
 "User: all tables in streamlit, ticker+spot should be frozen; 1-2 extra key columns may also be pinned",
 "NEEDS-CHECK","2026-08-03","SHIPPED: all 147 st.dataframe call sites routed through _pinned_df(), which pins up to 3 identity columns and merges any existing column_config (call site wins). New tables inherit it automatically. NOT CLOSED because the sticky behaviour cannot be asserted from the DOM - Streamlit renders tables to a canvas - so it needs the user to scroll a wide table right and confirm",
 "e83a651","P1","User to confirm Ticker/Company/Spot stay put when scrolling right"),
(98,"2026-08-03","User","Feature","Green/red bar chart of the last week/month in World Markets",
 "User wants to see, at a glance, how the market has traded recently rather than just today",
 "DONE","2026-08-03","_market_bars_png(): 4-panel daily percent-change bars, green up / red down, SPY/QQQ/IWM/DIA over 21 sessions, with an up-down tally and net return per panel. Reads stock_history only - no network call, works off-hours. Wired into /world under the map and regional table. Verified: 50 KB PNG. Immediately showed a breadth divergence the one-day snapshot hides - DIA had MORE up days (12/9) than QQQ (9/12) yet both finished negative, because QQQ net -3.5% came from a few violent red days",
 "-","P2","-"),
# ---- gaps found 2026-08-03 by extracting all 168 user turns from the raw session transcript
(99,"2026-07-22","User","Bug","MU estimated open showing as 0",
 "Raised early in the session; outcome was never recorded",
 "REJECTED","2026-08-03","Not reproducible and probably not a bug. No MU position is open (3 historical). Checked the maths directly: Est Open is a Black-Scholes price at dte-1, and at iv=0 it returns discounted intrinsic when ITM and exactly 0 when OTM - both correct. A ~$0.00 Est Open on a deep-OTM leg is the right answer, and the display already writes ~$0.00 rather than a bare 0 to signal near-zero rather than missing. Re-open if it recurs on a live position",
 "-","P2","-"),
(100,"2026-07-25","User","Bug","Paper trading splits GOOGL +1sh and +100sh into two rows",
 "User: it should behave like Robinhood/Fidelity and aggregate the lot",
 "DONE","2026-07-24","Already implemented - the audit flagged it only because no tracker row existed. Paper Trading groups STOCK lots by ticker with a weighted-average cost basis (Robinhood/Fidelity style), and the code comment cites this exact request. Options deliberately stay one row per contract: a 340C and a 345C are different instruments, not fungible the way shares are",
 "-","P2","-"),
(101,"2026-07-26","User","Research","Databento as a data source",
 "Asked alongside the OpenBB-vs-yfinance question",
 "NEEDS-CHECK","","Answered in conversation but never written down. Databento is paid, institutional-grade tick/OHLCV; the free lanes here are yfinance and OpenBB-cboe. Worth a proper written comparison only if the options-quote history gap becomes a blocker",
 "-","P3","Write up alongside the QuantConnect/ThetaData options-data note in ADOPTED.md Part 8"),
(102,"2026-07-26","User","Bug","Exit Planner wastes vertical space; constant scrolling",
 "User: what about space between lines, it is eating away space and I have to scroll down every time",
 "NEEDS-CHECK","","Transcript audit gap. Related to the bold-headers/readability work but logged separately because it is about DENSITY, not weight",
 "-","P2","Measure the page height; tighten margins/expanders"),
(103,"2026-07-26","User","Research","Adopt a page-management framework instead of hand-rolling",
 "User: check git and if you can adopt some frameworks for page management, why are you doing yourself",
 "DONE","2026-08-03","Answered in docs/ARCHITECTURE_PLAN.md section 6 with a measured comparison (Streamlit / Marimo / Reflex / NiceGUI / Dash / FastAPI+React). Conclusion: KEEP Streamlit. The pain - 22k-line reruns, NameError-class bugs, no testability - is caused by logic living in the UI, not by the framework, and 2,080 widget calls is a large sunk cost. Extract core/ first; reassess only once the UI is thin, at which point Marimo is the one worth trialling because it removes the rerun model that causes those specific bugs",
 "-","P2","-"),
(104,"2026-08-01","User","Question","Explain the credit > (1-POP) rule in plain terms",
 "User: what is that -- re: collect more than (1-POP) of width",
 "DONE","2026-08-01","Explained with worked examples and shipped as the Paid % vs Need % columns plus a per-row verdict (Real edge / Thin edge / Premium trap) in the basket panel. The single comparison that separates a real edge from the premium-selling trap",
 "9b80d13","P2","-"),
(105,"2026-08-02","User","Feature","Command Center: better writeup + more insightful, trade-oriented tables",
 "Asked together with the load-time complaint",
 "DONE","2026-08-03","Both halves now done. PERF was _uoa_scan vectorised 13.2s -> 0.18s (73x). CONTENT: added a Needs Action Today panel at the top - the page previously described STATE and never answered what to DO. Four rules, each carrying its WHY so it can be argued with: TAKE PROFIT at >=+50% (the 50%-exit test on this books own settled trades favoured closing over holding), DECIDE NOW at <=5 DTE (gamma and pin risk dominate the last week), TIME DECAY at 6-21 DTE while underwater (charm leans against long premium), REVIEW at <=-50%. When nothing qualifies it says so explicitly rather than rendering an empty table. Also reframed Fired Today: it now states plainly that fires are ACTIVITY not opportunity - they cluster hard and no directional scanner beats a coin flip once same-day fires stop double-counting. Verified live: all panels render, book reads correctly",
 "37a7049","P2","-"),
(106,"2026-08-02","User","Research","One backend + two front-ends; Streamlit alternatives",
 "User asked whether to split the architecture and whether something beats Streamlit",
 "DONE","2026-08-02","Full audit + migration plan written to docs/ARCHITECTURE_PLAN.md (7 sections). Measured baseline: 81 bot functions already called by the dashboard, 0 telegram refs in the dashboard, but 82 st. refs leaking INTO the bot. Recommendation: extract core/ with a CI guard banning UI imports, materialise scanner output, and KEEP Streamlit - the pain is logic living in the UI, not the framework. Nothing executed; awaiting the user analysis",
 "742d3aa","P1","User to review the plan, then start with the core/ extraction"),
(107,"2026-08-03","User","Process","Log every question and idea to the sheet BEFORE answering",
 "User: every question and idea should be logged to the sheet first",
 "DONE","2026-08-03","Strengthened the CLAUDE.md rule from log-then-work to LOG FIRST, then answer. A question IS a tracker item because the ANSWER is what gets lost - and the throwaway-sounding ones (why is X zero, what is this column) are exactly the ones that vanished. Also added tools/show_pending.py so no status summary is ever typed from memory again",
 "-","P1","-"),
(108,"2026-08-03","User","Question","How often does the per-leg live OPTION value refresh?",
 "Per-leg detail shows a live GOOG option value; user asked the update frequency",
 "DONE","2026-08-03","Answered from the code: _cached_option_chain ttl=300 (5 min) drives most option tables; _fetch_option_quote (Per-leg detail, Exit Planner) is UNCACHED so it refreshes on every page rerun; _cc_book ttl=120; _cached_price ttl=60; _cached_trades ttl=30. Two caveats matter more than the cadence: the quote function returns None when the market is CLOSED, and the value is a yfinance MID, which the fill study showed overstates a realistic exit",
 "-","P2","-"),
(109,"2026-08-03","Claude","Bug","Cannot DOM-verify pinned columns: Streamlit grid is canvas-rendered",
 "Playwright found 0 pinned cells even though config is applied and headers are in the right order",
 "NEEDS-CHECK","","st.dataframe renders via glide-data-grid into a CANVAS, so pinned/sticky state is not expressed in CSS and cannot be asserted from the DOM. Headers read back correctly (Ticker, Company, Spot $ first) and there are no errors, but the STICKY BEHAVIOUR itself is unverified by automation - it needs a human scroll or a screenshot diff",
 "-","P2","Verify by scrolling a wide table right and screenshotting, or accept as visually-confirmed-by-user"),
(110,"2026-08-03","User","Bug","Option tables still show previous EOD values, not live",
 "User: cache is 5 min but I still see EOD prev values",
 "DONE","2026-08-03","NOT a cache bug and NOT our SSL bug. _ssl_fix.ensure_ssl_trust() is called by BOTH surfaces and works - chain fetched in 0.4s. The problem is the SOURCE: at 09:43 ET Monday, yfinance returned bid=0 ask=0 on essentially every contract (SPY 3/214 non-zero bids, GOOG 0/42, QQQ 5/190) and lastTradeDate on the most-traded strikes read 2026-07-31 20:03 UTC - Friday. So yfinance was still serving the previous session chain 13 minutes after the open. Our code is behaving correctly by falling back rather than printing a fake 0; what is missing is that the UI does not SAY the quote is stale",
 "-","P1","Show quote AGE next to option values (as of Fri 16:03) and prefer options_openbb bid/ask when the yfinance chain is stale"),
(111,"2026-08-03","User","Feature","Day low-high as a line graph, not just text",
 "User: day l-h in this create as line graph, I said earlier - a repeat ask",
 "DONE","2026-08-03","Added a Day path column: st.column_config.LineChartColumn fed with today's real 1-minute closes from US_intraday.db (one query for the whole watchlist, last ~120 bars per name). It shows the SHAPE of the session, not just its endpoints, sitting next to the existing Day position bar. Tickers outside the intraday lane (~31 names) get a blank cell rather than a fabricated line. Verified by reading the grid headers directly: Ticker | Company | Spot $ | Day % | Day path | Day position | 52w position | ...",
 "-","P1","-"),
(112,"2026-08-03","User","Feature","Show a refresh timestamp under Per-leg detail",
 "User: can you refresh time after this",
 "DONE","2026-08-03","Per-leg detail now shows: refresh clock, market state (OPEN/PRE/AFTER/CLOSED), and the newest lastTradeDate found in the option chain itself. If that trade date is a previous session it prints an explicit warning that the Now column is a stale mark, not a live price - which is exactly the condition seen at 09:43 ET Monday when yfinance was still serving Fridays chain. Verified live: Refreshed 09:47:28 - market OPEN",
 "-","P1","-"),
(113,"2026-08-03","User","Bug","Merged GEX/Gamma pages are nowhere to be found",
 "User: yesterday you merged gamma things, where are they, I do not see anywhere",
 "DONE","2026-08-03","NOT lost - the merge shipped and works. Verified live: navigated to the page, sub-view radio renders, all three views present, zero errors. It is at Sidebar > section 'Trade Ideas' > 'GEX Command', with a GEX view radio switching Co-Pilot / GEX Profile / Gamma Wall Advisor. The user could not find it because it sits under Trade Ideas rather than where GEX Profile used to be, and the jump box virtualises to ~10 options until you type. Caveat recorded: my nav enumeration returned an EMPTY list for GEX/Gamma because of that virtualisation - trusting it would have produced a false 'page is missing' report",
 "-","P1","Consider a one-line note under the old section pointing to the new home"),
(114,"2026-08-03","User","Bug","GOOG call wall 375 BELOW put wall 380 - structurally impossible",
 "User: seems strange. Spot is ~356, so both walls sit above spot and in the wrong order",
 "DONE","2026-08-03","Root cause found in compute_walls(), the OI-based wall function (the project has THREE wall definitions: _compute_gex signed-GEX walls, analyze_inst_signals OI clusters, and this one). It took the global max-OI strike per side with NO reference to spot, so both walls could land on the same side of price and invert - GOOG printed call 375 with put 380 while spot was 356. Fixed by restricting each side to its own half of the chain (call wall from strikes >= spot, put wall from strikes <= spot), falling back to the unconstrained max only if that half is empty. Verified across 8 tickers: 0 inversions",
 "-","P1","Still worth reconciling the THREE competing wall definitions into one"),
(115,"2026-08-03","User","Bug","ADR tickers rejected as invalid on add (KSPI)",
 "User: KSPI does not look like a valid/quoted ticker - not added. It is an ADR; wants ADRs supported across the data flow",
 "DONE","2026-08-03","Not an ADR problem at all - the validator was broken for EVERY ticker. yfinance FastInfo keys are camelCase (lastPrice), so fi.get(last_price) returned None for GOOG, NVDA, everything. Validation therefore only ever passed through the DB/history fallback, which means any symbol NOT already in our DB was rejected - ADRs being the obvious casualty. KSPI is quoted at $92.02. Fixed in BOTH validators (dashboard + bot) to use attribute access with a 5d history last resort. Verified: KSPI/BABA/TSM/NVDA all valid, a typo (ZZZZQQ) still correctly rejected",
 "-","P1","-"),
(116,"2026-08-03","User","Bug","GEX Co-Pilot shows only the checklist - no gamma wall charts",
 "User: I see only this, gamma wall charts and other are missing",
 "DONE","2026-08-03","Corrected the interpretation. MERGE = move everything onto ONE page, all visible - my first pass split the three former pages behind a sidebar radio, which only moved the hiding place, and the user reported the wall charts as missing because one sub-view rendered at a time. Removed the radio; all three sections (Co-Pilot, GEX Profile, Gamma Wall Advisor) now render stacked on the single page. Verified live: all three headers present, radio gone, zero exceptions. SEPARATE follow-up: the Advisor charts still need that sections own ticker input/Analyze button - pre-existing behaviour, not caused by the merge",
 "-","P1","Auto-run the Advisor for the selected ticker so its charts draw without a second click"),
(117,"2026-08-03","Claude","Bug","Volume surge check reads 0.0x its 20-bar average",
 "Seen in the live Mode 2 output for GOOG during market hours",
 "DONE","2026-08-03","Confirmed and fixed. The newest 1m row is a PARTIAL bar still filling - GOOG 10:50 had volume 0 while 10:46-10:49 ran 33-48k - so the surge ratio was 0.0x and the volume leg failed for everything, all session. _gex_confirm now drops a trailing zero-volume bar. GOOG went 0.0x -> 0.68x (still no surge, but now a real measurement)",
 "-","P1","-"),
(118,"2026-08-03","User","Bug","EOD premium 7.28 does not match the captured chain (11.50 mid)",
 "User: why is EOD premium 7.28",
 "DONE","2026-08-03","Root cause: the label was wrong, not the arithmetic. When _fetch_option_mid returns None - which it does all session while yfinance serves bid=ask=0 - the code fell through to a BLACK-SCHOLES price computed at TODAYS live spot with historical vol, and displayed it as EOD Premium. It was neither EOD nor a market price. Fixed to prefer our own captured chain via _bb_quote first (GOOG 355P 2026-07-31: bid 11.00 / ask 12.00 -> mid 11.50, iv 0.323, delta -0.454), falling back to the model only when we have no capture. Entry 11.21 vs a true Friday mark of 11.50 means the leg was roughly FLAT, not -35%",
 "-","P0","DOM-verify the metric on the Portfolio page"),
(119,"2026-08-03","User","Bug","OI Roll Detector shows EXPIRED expiries",
 "User: why is it showing done ones, it should show live/intraday and the NEXT expiries",
 "DONE","2026-08-03","The roll query pulls the latest CAPTURE date (usually the previous session) and had NO expiry filter at all, so on Monday it reported rolls into a Friday expiry that had already settled. Now filters expiry_date >= today (ISO dates sort lexically). GOOG went from expiries led by 2026-07-31 to 2026-08-07 / 08-21 / 09-04, zero expired",
 "-","P1","-"),
(120,"2026-08-03","Claude","Bug","'Right at the call wall' fires when price has CLEARED the wall",
 "Same output: says price cleared both walls, then warns it is right at the call wall",
 "DONE","2026-08-03","Fixed. The check was spot >= cw*0.99, true no matter how far above the wall price went, so a price that had cleared the call wall by 11% still printed right at the call wall directly beneath a sentence saying it had cleared both walls. Now a genuine proximity band on both sides: cw*0.99 <= spot <= cw*1.02 for the call wall, pw*0.98 <= spot <= pw*1.01 for the put wall",
 "-","P1","-"),
(121,"2026-08-03","User","Bug","Data download does not start on its own when the laptop is opened",
 "User: why is data download not working on its own when i open laptop",
 "DONE","2026-08-07","NOT BROKEN - verified against the DB rather than the log: options_openbb has 2026-08-06 (191,434 rows), 08-05, 08-04; stock_daily 732 tickers; parquet backups present for all three days. Yesterdays run captured 734 tickers rc=0 in 103 min. The task fired on logon today at 07:29 and correctly reported Already ran for 2026-08-06. The Disabled state is misleading: its logon/boot triggers fire anyway, 0 missed runs. It cannot be enabled from a normal shell because its ACL grants this account Read only while the other tasks grant FullControl - it was registered from an elevated prompt. Fix needs an admin PowerShell: Enable-ScheduledTask -TaskName NYSE_OffHours_Chain",
 "78ab2ef","P0","User: run an elevated PowerShell once to clear the Disabled flag (cosmetic - it runs regardless)"),
(122,"2026-08-03","User","Bug","Telegram commands not responding",
 "User: why telegram commands not working",
 "DONE","2026-08-07","DNS failure at wake, not a code fault: httpx.ConnectError [Errno 11001] getaddrinfo failed at 07:38 - the bot tried api.telegram.org before wifi reconnected. Recovered on its own; verified live DNS resolves 149.154.166.110 and getMe returns @Analyst_Somu_AI_bot, with 61 slash commands registered at the 07:32 restart. The durable fix is the watchdog (ID 123), which was itself dead",
 "78ab2ef","P0","-"),
(123,"2026-08-07","Claude","Bug","TelegramBotWatchdog has 115 missed runs and a failing exit code",
 "Found while diagnosing why Telegram commands were dead: the watchdog that exists to restart the bot has not been working",
 "DONE","2026-08-07","ROOT CAUSE: bot_watchdog.ps1 DID NOT EXIST. The task had pointed at that path since registration, so every run failed to open the -File target - 115 missed runs, rc=0xFFFD0000. Wrote it: matches on COMMAND LINE not image name (several python.exe run here, so a bare name check always looks healthy), and refuses to restart when DNS for api.telegram.org fails, because a wake-from-sleep blip is not a dead bot and restarting into a dead network just loses the job queue. Testing caught a second real bug: two overlapping runs both calling Add-Content threw file-in-use, and with ErrorActionPreference=Stop that killed the whole watchdog - logging now retries then gives up silently. Verified: no-op when healthy (bot pid unchanged, nothing logged), correct branch when down, 3 concurrent runs all exit 0",
 "78ab2ef","P1","-"),
(124,"2026-08-07","User","Bug","CMD windows popping up and closing every few minutes",
 "User: why is cmd popping and closing frequently, its irritating",
 "DONE","2026-08-07","MY FAULT, from enabling TelegramBotWatchdog an hour earlier: it fired every 5 MINUTES running powershell.exe under an Interactive logon with Hidden=False, so a console flashed 288 times a day. PowerShells own -WindowStyle Hidden does not help - the console is allocated before PowerShell can act on the flag. Fixed with a WScript.Shell.Run launcher (intWindowStyle=0 never allocates a console) and relaxed 5min -> 10min, which is fine because the DNS guard stops it thrashing and <=10 min of bot downtime is acceptable. Also audited every child-process spawn in the bot: all had CREATE_NO_WINDOW except the manual data-refresh at line 10745, which popped a console for up to 10 minutes - now consistent. Verified: task rc=0, bot pid unchanged, no stray consoles",
 "00f61e0","P1","-"),
(125,"2026-08-07","User","Feature","Catalyst Radar: explain each event, keep it 2-3 days AFTER, add consensus vs actual",
 "User: I do not know what NFP is. Whatever you show needs a writeup - what it is, frequency, market expectation, actual value - keep showing the event 2-3 days after it happens, what the possible outcomes are based on the real actual value, and trade advice",
 "DONE","2026-08-07","Added _MACRO_EVENT_INFO: every catalyst now carries full name, what it measures in plain English, frequency, why it moves markets, and a how-to-read table of outcome -> implication. Window extended to show events 3 days AFTER they print, because the reaction is the tradeable part. For events with a BLS series the ACTUAL is fetched and shown. Deliberately reports actual vs PRIOR, not vs consensus: no free feed carries market expectations, and inventing a consensus would be fabrication. NFP specifically reports the CHANGE (-23k jobs, jobs LOST, weak) rather than the payroll LEVEL (158,858k) - the level is technically true and useless",
 "-","P1","-"),
(126,"2026-08-07","User","Feature","Catch-up alerts: fire on laptop open, then hourly",
 "User: if I am not opening before market but open mid-session, I lose the time-based scheduled alerts",
 "DONE","2026-08-07","run_daily fires once; a sleeping laptop loses that push for the day. All 7 morning alerts now route through _run_alert_once, which records the send in alert_dedup, and catchup_alert sweeps 90s after startup then hourly, firing anything whose time has passed that has not gone out. The dedup INSERT is what makes double-calling safe. Weekday-gated, and it prefixes a Catch-up notice so a 11am briefing is not mistaken for an 8:15 one",
 "-","P1","-"),
(127,"2026-08-07","User","Bug","MARKET ANOMALY alert fires far too often",
 "User: SNDK +9.3% keeps coming, can we trim it to positions or a smaller set",
 "DONE","2026-08-07","TWO causes. (1) The dedup key was type + DESCRIPTION, and the description reads SNDK +9.3% from open - the percentage was IN the key, so every tick minted a new one. Confirmed in alert_dedup: TICKER_SHOCK_SNDK +9.3% and +10.4% logged as separate alerts the same day. Key is now type + TICKER = one alert per name per day. (2) No relevance filter: a 5% intraday move is ordinary across 700 names. Now alerts only on tickers held or watchlisted, plus the index/vol complex; anything else must clear 12% to interrupt",
 "-","P1","-"),
(128,"2026-08-07","User","Feature","Writeup for every significant market move - cause, knock-on, trade advice",
 "User: gold +3.9% and silver +4.7% - why. Wants a section explaining every significant move: what happened, what led to it, likely repercussions and future moves, trade advice per asset, across indices/commodities, using news + macro + micro + events, plus the flow of what rises or falls as a consequence",
 "DONE","2026-08-07","Added /whymoved plus a WHY IT MOVED section inside the next-day game plan. Per significant move (thresholds by class: 2% commodities, 1% US, 1.2% intl) it gives what the asset is, what drives it, the likely driver from todays headlines, the mechanical knock-on chain, and a trade angle. The honesty split is deliberate and load-bearing: KNOCK-ON is mechanical and stated as fact (gold up lifts miners with 2-3x leverage), DRIVER is inferred and says UNCONFIRMED when no headline names a cause - inventing a narrative is the easy failure here. Verified live on gold +4.2% / silver +5.0%; both correctly reported driver UNCONFIRMED because the news feed carries no commodity headline",
 "-","P1","GAP FOUND: the RSS mix is equity-heavy, so commodity moves rarely match a headline. A commodity news source would make the driver line useful rather than honest-but-empty"),
(129,"2026-08-07","Claude","Bug","Bot failed to start: dt_time NameError in _sched_once",
 "Introduced by the catch-up alert work an hour earlier",
 "DONE","2026-08-07","main() does `from datetime import time as dt_time` LOCALLY, so the module-level helper could not see it. The bot died on startup and only the redirected stderr showed it - telegram_bot.log stopped at Opened dashboard with no traceback, which is why it looked like a hang. Fixed by importing dt_time inside _sched_once, then audited the other three new helpers for the same class of error. Bot verified back up: pid 34080, getUpdates 200 OK, riskoff_alert executed",
 "-","P0","Lesson: a helper hoisted out of main() cannot rely on main()-local imports"),
(130,"2026-08-07","User","Research","Scenario tools and flow charts - what is proven and worth adopting",
 "User: check git and finance sites for well-proven, time-tested scenario tools and flow charts; tabulate what could add value",
 "DONE","2026-08-07","Surveyed and API-VERIFIED 7 candidates; 4 of 7 fail. The trap this time is pyfolio: 6,390 stars but last push 2023-12-23, Quantopian defunct - 20x the stars of the repo actually worth having. THE FIND is fortitudo.tech (303 stars, 4 contributors, active): Entropy Pooling, Meucci 2008. It answers what this system cannot - if gold rallies 5%, what happens to MY book - by re-weighting the JOINT historical distribution under a view rather than shocking one asset in isolation. Fits because we hold a real joint panel (stock_history to 1990 incl 2000/2008/2020/2022). On flowcharts: Merrill Lynch Investment Clock (2004) is the one worth building - falsifiable asset-leadership claims testable on our own history. Rejected Riskfolio-Lib (duplicates /allocate), quantstats (duplicates /recperf), 3 solo repos (QuantMuse pattern), Elliott Wave/Gann (unfalsifiable). ADOPTED.md Part 11",
 "-","P2","Neither adopted - see IDs 131/132"),
(133,"2026-08-07","User","Feature","Ticker view: explain the jargon, organise it better",
 "User on the GOOG panel: needs rephrasing and more description, keep the table, I do not know what MOM or golden-cross mean",
 "DONE","2026-08-07","Signal codes replaced with plain names (Mom -> Momentum, OI -> Open interest, 24M -> All signals) and a What these mean glossary printed under the table, which is kept as a table as asked. Hit% now carries a legend saying 50% is a coin flip. golden-cross replaced with: the 50-day average is ABOVE the 200-day, the conventional long-term uptrend marker - and death-cross likewise. The inference line uses the friendly name too",
 "-","P1","-"),
(134,"2026-08-07","User","Feature","Catalyst Radar: show the 3 days BEFORE an event, split into two tables",
 "User: add what happens 3 days before an event like this, tabulate in two different tables, organise more readably",
 "DONE","2026-08-07","Split into two scannable tables (COMING UP / JUST HAPPENED) with the full explainer underneath, so nothing is lost. Then MEASURED the pre-event premise instead of asserting it: across 113 NFP releases since 2015, SPY returns -0.04% over the three sessions into the print vs a +0.19% baseline (t=-1.35, p=0.18), the print day +0.09% vs +0.06% (p=0.80), the day after -0.04% (p=0.45). NONE significant. So the section now states plainly that the 3 days into an event carry no measurable directional edge, and that the reliable part is IV inflating then collapsing - the event trade is about VOLATILITY, not direction. Building a pre-event drift feature would have shipped an edge that does not exist",
 "-","P1","-"),
(131,"2026-08-07","Claude","Research","Build + TEST the Merrill Lynch Investment Clock",
 "From the Part 11 survey: the only finance flowchart making a falsifiable claim",
 "QUEUED","","Two axes (growth rising/falling, inflation rising/falling) -> four quadrants with expected asset leadership (Reflation bonds, Recovery stocks, Overheat commodities, Stagflation cash). TEST FIRST against 1990-2026 via tools/walkforward.py; if quadrant leadership does not hold out-of-sample, report that and stop rather than shipping it",
 "-","P2","-"),
(132,"2026-08-07","Claude","Research","Trial Entropy Pooling (fortitudo.tech) for book scenarios",
 "The one genuinely additive library from the Part 11 survey",
 "QUEUED","","Feed stock_history as the joint scenario panel, ask a view like gold +5%, compare the implied book move against what actually happened on real gold-rally days. If they disagree badly the panel is wrong, not the method. Would replace hand-picked crash windows with a general what-if answer",
 "-","P2","-"),
(135,"2026-08-07","User","Feature","Spell out sector abbreviations and use relevant emoji",
 "User on the VIX/leaders line: add something simple for CALM, Tech, Hlth, Engy, Finl and anything else in that section - the emoji should be relevant to the thing",
 "DONE","2026-08-07","Sector abbreviations expanded with a depicting emoji: Tech -> 💻 Technology, Finl -> 🏦 Financials, Engy -> 🛢️ Energy, Hlth -> 🏥 Health Care, plus Industrials/Discretionary/Staples/Utilities/Materials/Real Estate/Communications. VIX line rewritten from a bare CALM label to a mood emoji scaled across five bands PLUS the translation that actually matters - the implied daily S&P move (VIX/15.87) - and whether premium is cheap to buy or good to sell at that level",
 "-","P2","-"),
(136,"2026-08-07","User","Feature","/catchup command + a catch-up panel in Streamlit",
 "User saw the catch-up push working and asked for it on demand: a Telegram command, plus a top section on Market Overview and Command Center",
 "DONE","2026-08-07","/catchup sends every briefing DUE so far today, deliberately bypassing the dedup - the scheduled sweep only fires what was missed, but asking explicitly should deliver regardless of whether it already went. Streamlit gained a _catchup_panel at the top of Market Overview and Command Center reading the same alert_dedup rows: green when everything due has gone, an amber warning naming the missing ones and pointing at /catchup when not. Verified live: All briefings due so far today have been sent",
 "-","P1","-"),
(137,"2026-08-07","User","Bug","NFP block missing consensus, unemployment rate, revisions and historical context",
 "User pasted the real release: -23k vs +85k expected, unemployment 4.1% vs 4.2% expected, June revised DOWN -37k, 3rd biggest monthly job loss since 2020. Ours showed only -23k weak",
 "DONE","2026-08-07","Three of the four gaps closed from data we already had. UNEMPLOYMENT RATE: LNS14000000 lands in the same 8:30 release and is now shown - 4.1% vs prior 4.2%, matching the real release exactly, with the note that a falling rate alongside job losses usually means people LEFT the workforce. HISTORICAL CONTEXT: the print is now ranked against the trailing series (4th weakest of the last 18 months) - the same calculation behind the 3rd-biggest-since-2020 line. CONSENSUS: no free calendar carries it, but the COVERAGE does, so the block now quotes the release stories - live output pulled Reuters -unexpectedly decline, unemployment eases to 4.1- and Detroit News -June report is revised downward-, which supplies both the vs-expected and the revision. REVISIONS from our own series still need vintage storage (ID 93)",
 "-","P1","-"),
(138,"2026-08-07","User","Feature","Breaking-news section tied to positions and relevant alerts",
 "User: add a breaking news section in our positions or relevant alerts",
 "DONE","2026-08-07","Added /breaking plus a BREAKING block at the TOP of the next-day game plan - a halt on a name you own outranks any market colour. Scans Google News per held/watchlisted ticker and keeps only headline TYPES that historically move a stock (halt, guidance cut, M&A, downgrade, short report, FDA, investigation), each carrying WHY it matters to a position. Two precision fixes during testing: a SUBJECT check, because Wells Fargo downgrades Allstate was firing under WFC when the bank is the ANALYST not the subject; and an upgrade-cycle guard, because a product cycle is not a rating change. Verified live: surfaced DDOG plunging 19% despite an earnings beat, and an AAPL downgrade",
 "-","P1","-"),
(139,"2026-08-07","User","Feature","WHAT JUST HAPPENED: tabulate it and attach the event numbers",
 "User: keep it all in tabular format and more insightful. The timeline says 08:30 Jobs Report release but gives no numbers, even though the release time has already passed - tabulate previous / expected / actual",
 "DONE","2026-08-07","ROOT CAUSE of the empty timeline line: the engine ALREADY had code to print actual/estimate/prior, but ev[actual] was never populated - the calendar supplies name and time only, nothing attached the print. So a release whose time had passed still read 08:30 ET Jobs Report release with no numbers. Now enriched from the bot BLS reader built for ID 137, lazily imported to avoid a circular import, with fuzzy name mapping (Jobs Report / Nonfarm Payrolls -> NFP, CPI, PCE, FOMC). THE DATA section converted to a table carrying the print, expected, the companion series and the historical rank. Verified: Jobs Report resolves to -23k jobs, unemployment 4.1% prior 4.2%, 4th weakest of the last 18 months",
 "-","P1","-"),
(140,"2026-08-07","User","Feature","Fear and Greed history chart: 1d/1w/1m/3m/1y/5y",
 "User wants to see how greed has evolved, not just todays reading",
 "IN-PROGRESS","2026-08-07","Logged. CNN graphdata API carries history but failed on first call with DNS getaddrinfo - the same intermittent wake-from-sleep failure seen this morning. Retry, and store our own daily snapshots so history accrues locally regardless",
 "-","P2","-"),
(141,"2026-08-07","Claude","Bug","12 commands had handlers but were missing from the Telegram menu",
 "Found while confirming today's work went live: the bot logged 61 registered commands but the file defines 73 handlers",
 "DONE","2026-08-07","Every new command shipped today (/breaking /catchup /whymoved) plus 9 older ones (/debate /flow /capflow /world /recperf /status /freq /reopen /menu) existed ONLY if you already knew to type them - they never appeared in Telegram autocomplete. Diffed add_handler(CommandHandler(...)) against BotCommand(...) to find them rather than eyeballing. All 12 added; menu now 73/73. Telegram allows 100, so there was never a capacity reason for the gap",
 "-","P1","Add a startup assertion so a handler without a menu entry is logged, not silently invisible"),
(142,"2026-08-07","User","Feature","Auto-trigger the new commands on a schedule",
 "User: can you send auto triggers for every sometime - for /breaking, /whymoved, /digest",
 "DONE","2026-08-07","breaking_alert every 2h during the day, CONTENT-GATED not just timed: it pushes only severity-3 news (halt, guidance cut, M&A, short report, FDA) on a name you hold, and only if that exact headline has not already gone out - dedup keyed on ticker+headline. Lower-severity items stay on demand via /breaking. whymoved_alert at ~4:45pm ET explains the days significant moves post-close, registered through _sched_once so it also gets caught up if the laptop was asleep. Deliberately NOT a plain timer: a push that fires regardless of content is exactly how the SNDK anomaly spam trained the channel to be ignored earlier today",
 "-","P1","-"),
(143,"2026-08-07","Claude","Bug","Eight scheduled alerts logged as partial, untraceable",
 "Spotted reading the startup log after wiring the catch-up jobs",
 "DONE","2026-08-07","_sched_once wraps each alert in functools.partial, and without an explicit name= the scheduler logs every one of them as job partial. Eight different briefings were indistinguishable in the log, so a failure could not be traced back to which alert broke. Passing name=key fixes it; the log now shows morning_alert, catalyst_alert, plan_alert, whymoved_alert and the rest by name",
 "-","P2","-"),
(144,"2026-08-07","User","Bug","Game plan truncated - commodities lost, and news should be at the END",
 "User: why are commodities not coming, I asked to ADD detail not remove what was there. Also news should go to the end not the start",
 "DONE","2026-08-07","CONFIRMED one cause for both complaints. _send_plan sent the whole report in ONE reply_text, and the plan is 9,381 chars against Telegrams 4,096 cap - so everything past the cap was silently lost. COMMODITIES sat at char 4,056, right at the boundary, which is exactly why it looked deleted when nothing had been removed. Added _chunk_on_sections, which splits on blank lines so a <pre> table is never cut in half (a half-table is worse than none) and keeps the keyboard on the last message only. Moved BREAKING from the top to the END as asked. Verified: 9,338 chars -> 3 chunks of 3623/2716/2995, every chunk has balanced pre tags, COMMODITIES now at char 1,049 and BREAKING at 6,348, both surviving",
 "-","P0","-"),
(145,"2026-08-07","User","Bug","Digest rendering raw HTML entities (&lt;/pre&gt;, &lt;i&gt;)",
 "User pasted digest output showing escaped tags as literal text instead of formatting",
 "DONE","2026-08-07","ROOT CAUSE, and it is the same class as the /plan truncation. Five senders chunked with a blind txt[i:i+3900], which cuts straight through an HTML tag. PROVEN on the real digest: chunk 0 ended with an unbalanced <b>, its closing tag falling into chunk 1. Telegram rejects a message with unbalanced entities, the sanitize wrapper catches the error and falls back to escaping EVERY < to &lt; - so the whole message arrives as literal tag text. That is exactly the &lt;/pre&gt; the user saw. Routed all 5 chunkers through _chunk_on_sections, which splits on blank lines. Verified: digest 4,987 chars -> 2 chunks, every pre/i/b tag balanced in both",
 "-","P0","-"),
(146,"2026-08-07","User","Feature","Payoff + beta-weighted P&L charts on the Portfolio page",
 "User: add this kind of chart and writeup to the portfolio one - the per-position payoff-at-expiry chart and the P&L vs SPY move panel that Telegram already sends",
 "DONE","2026-08-07","Added a Risk & payoff charts panel to the Streamlit Portfolio page, calling the SAME engine functions Telegram uses (_plan_portfolio_png, _plan_payoff_png, _pl_bounds, _pl_analytics) rather than reimplementing the maths, so the two surfaces cannot drift. Beta-weighted book sensitivity with per-1%-SPY and +/-2% scenarios, plus a per-ticker payoff-at-expiry chart with max profit/loss, POP and EV. Values verified IDENTICAL to the Telegram output the user pasted: -224 per 1% SPY, 407/-488 at -/+2%, GOOG max P 34,378 max L -1,121, POP 35%, EV -80, B/E 344. VERIFICATION NOTE: my first DOM check reported the metrics MISSING - that was wrong, Streamlit uppercases metric labels and my match was case-sensitive",
 "-","P1","-"),
(147,"2026-08-07","User","Feature","Market heatmap treemap, Telegram + Streamlit, live and EOD",
 "User shared a TradingView-style sector treemap: tiles sized by market cap, coloured by percent change, grouped by sector",
 "DONE","2026-08-07","/heatmap in Telegram (PNG via kaleido) and an interactive panel on Market Overview, sharing ONE engine function _heatmap_frame so there is no duplicate implementation. Built entirely from the DB - daily_fundamentals market_cap+sector, stock_daily moves - so no new source and no API key. Live during market hours (top 40 names refreshed with live quotes; a per-ticker quote for all 180 would be far too slow) and last-completed-session off-hours, with the as-of stated on the chart. Telegram also gets the numbers as tables, because a picture cannot be quoted or read back. A REAL BUG was caught only by opening the PNG: branchvalues=total requires each parent to EQUAL the sum of its children, and appending sector rows with value 0 made every parent smaller than its children, so Plotly silently dropped the entire tree and rendered a blank chart - 65KB of nothing. Verified visually after the fix (373KB, NVDA +2.3%, PLTR +10.3%, GOOGL -1.0% correctly placed) and in the live DOM: 180 names across 11 sectors",
 "-","P1","-"),
(148,"2026-08-07","User","Process","Regression pass over every change made today",
 "User: test all changes properly",
 "DONE","2026-08-07","Wrote tools/test_regression_20260807.py - 12 checks, each asserting the SPECIFIC defect cannot recur rather than that code merely runs. Examples: the heatmap check fails if the PNG is under 200KB because the blank-tree bug produced 65KB of black background that still counted as a successful write; the chunker checks assert tag BALANCE per chunk, which is what Telegram actually rejects; the menu check diffs handlers against BotCommand entries. Result 12/12 pass. Live confirmation too: getMe OK, 74 commands live on Telegram including heatmap/breaking/catchup/whymoved/screen, and 33 scheduled jobs registered by name",
 "-","P1","Re-run this file after any change to the send/chunk path"),
(149,"2026-08-07","User","Feature","Add USD/INR to the FX & RATES section",
 "User: FX & RATES (2/4 up) - add usd inr pair also",
 "DONE","2026-08-07","Added INR=X as USD/INR with the India flag. The existing precision rule handled it correctly with no change needed - above 10 formats to 2dp, so 95.20 rather than the 4dp used for EUR/USD. Verified live: FX & RATES now reads 5 instruments, USD/JPY 157.74, EUR/USD 1.1562, USD/INR 95.20, DXY 99.60, US 10Y 4.66%",
 "-","P2","-"),
(150,"2026-08-07","User","Feature","/breaking should cover ALL market-important events, with my trades as a separate section",
 "User: this should be on all market imp events, a separate section for my trades",
 "DONE","2026-08-07","/breaking now has TWO sections: MARKET-WIDE first (policy, inflation, tariffs, broad risk moves, circuit breakers) then YOUR POSITIONS. Kept separate on purpose - the Fed moving and a stock you own halting are different kinds of news, and interleaving them buries the one needing action. Two precision fixes found by reading the output: CEO Sells $36M was labelled leadership change because ceo matched first, now correctly insider SELLING - the filing is fact, the motive is not; and MDB Capital Holdings (MDBH) was firing under MDB, now excluded because a longer all-caps symbol in parentheses means a different company",
 "-","P1","-"),
(151,"2026-08-07","Claude","Bug","BLS daily API quota exhausted - unemployment line vanished silently",
 "Caught by the regression pass: the NFP check went from PASS to unemp=None between runs",
 "DONE","2026-08-07","The public BLS API allows ~25 requests/day per IP with no key, and _macro_event_actual fetched TWO uncached series on EVERY render - a morning brief plus a couple of digests would exhaust it, after which the unemployment line simply disappeared with no error. My own testing hit the ceiling, which is how it surfaced. Added _bls_series with a 6h cache (the data is MONTHLY - per-render fetching was never justified), which serves stale data rather than blank on a quota response, and logs the BLS message instead of swallowing it. Regression test updated to report quota exhaustion as SKIPPED-environment rather than a code failure, so the check is not trained to be ignored",
 "-","P1","Optional: a free BLS registration key raises the limit to 500/day on API v2"),
(152,"2026-08-07","User","Question","Change IP to get past the BLS rate limit?",
 "User: can you change ip and try it",
 "REJECTED","2026-08-07","Declined - rotating IPs to evade a providers published rate limit is circumventing their usage policy, and it would break again unpredictably. Did the sanctioned equivalent instead: BLS issues a FREE registration key that moves you from the ~25/day unregistered v1 endpoint to 500/day on v2. Wired support in - set BLS_API_KEY in api_keys.env and _bls_series switches to v2 automatically; with no key it stays on v1 and leans on the new 6h cache. Register at https://data.bls.gov/registrationEngine/ (free, instant). Combined with the cache this is 1 request per 6h per series instead of 2 per render, so even the unregistered limit is comfortable",
 "-","P2","USER: register for a free BLS key and add BLS_API_KEY=... to api_keys.env"),
(153,"2026-08-07","User","Feature","Source macro from a key we already hold, and fetch on a smart cadence",
 "User: can we get this from another site where we already have keys; and we do not need to check all the time - once early morning for revisions, then every 30min on a scheduled release day",
 "DONE","2026-08-07","ALTERNATIVE SOURCE TESTED AND REJECTED: AlphaVantage (key already held) does serve NONFARM_PAYROLL, but its July level is 158,649 against BLS 158,858 - a different vintage or seasonal adjustment, so the headline month-over-month change would not match the number everyone quotes. Its free tier is also 25/day, the same constraint, and UNEMPLOYMENT and CPI rate-limited after three calls. Swapping would trade a quota problem for a WRONG NUMBER problem. The cadence idea was the right fix and is now implemented: _bls_refresh_ttl returns 30 min only during 08:00-10:30 ET on an actual release day (NFP first Friday, or a scheduled CPI/PCE/FOMC date) and otherwise holds until the next early morning, so one refresh a day picks up revisions. Verified across four scenarios: NFP day 08:45 -> 1800s, NFP day 11:00 -> 19h, normal Tuesday -> 21h, CPI date 08:30 -> 1800s",
 "-","P1","-"),
]

def build():
    wb = Workbook(); ws = wb.active; ws.title = "Ideas & Questions"
    hdr_fill = PatternFill("solid", fgColor="1F3864")
    hdr_font = Font(bold=True, color="FFFFFF", size=11)
    thin = Side(style="thin", color="BFBFBF")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)
    status_fill = {
        "DONE":      PatternFill("solid", fgColor="C6EFCE"),
        "QUEUED":    PatternFill("solid", fgColor="FFF2CC"),
        "BLOCKED":   PatternFill("solid", fgColor="F8CBAD"),
        "REJECTED":  PatternFill("solid", fgColor="D9D9D9"),
        "WITHDRAWN": PatternFill("solid", fgColor="FFC7CE"),
        "USER-ACTION": PatternFill("solid", fgColor="BDD7EE"),
    }
    prio_font = {"P0": Font(bold=True, color="9C0006"), "P1": Font(bold=True, color="974706")}

    ws.append(COLS)
    for i, cell in enumerate(ws[1], 1):
        cell.fill = hdr_fill; cell.font = hdr_font; cell.border = border
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    for r in ROWS:
        ws.append(list(r))
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, max_col=len(COLS)):
        for c in row:
            c.border = border
            c.alignment = Alignment(vertical="top", wrap_text=True)
        st = row[COLS.index("Status")].value
        if st in status_fill:
            row[COLS.index("Status")].fill = status_fill[st]
            row[COLS.index("Status")].font = Font(bold=True)
        pr = row[COLS.index("Priority")].value
        if pr in prio_font:
            row[COLS.index("Priority")].font = prio_font[pr]

    widths = {"ID":5,"Date Added":12,"Raised By":10,"Category":13,"Idea / Question":34,
              "Detail":42,"Status":12,"Date Actioned":13,"Outcome / Evidence":62,
              "Commit":10,"Priority":8,"Next Step":34}
    for i, c in enumerate(COLS, 1):
        ws.column_dimensions[get_column_letter(i)].width = widths.get(c, 18)
    ws.row_dimensions[1].height = 30
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:{get_column_letter(len(COLS))}{ws.max_row}"

    # summary sheet
    s = wb.create_sheet("Summary")
    s.append(["Status", "Count"]);
    counts = {}
    for r in ROWS: counts[r[6]] = counts.get(r[6], 0) + 1
    for k, v in sorted(counts.items(), key=lambda x: -x[1]): s.append([k, v])
    s.append([]); s.append(["Category", "Count"])
    cc = {}
    for r in ROWS: cc[r[3]] = cc.get(r[3], 0) + 1
    for k, v in sorted(cc.items(), key=lambda x: -x[1]): s.append([k, v])
    for row in s.iter_rows():
        for c in row:
            if c.row == 1 or (c.value in ("Category",) and c.column == 1):
                c.font = Font(bold=True)
    s.column_dimensions["A"].width = 16; s.column_dimensions["B"].width = 8

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    wb.save(OUT)
    print(f"wrote {OUT}  ({len(ROWS)} rows)")
    for k, v in sorted(counts.items(), key=lambda x: -x[1]):
        print(f"   {k:12s} {v}")

if __name__ == "__main__":
    build()
